[2025-06-03T15:16:46.189+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usd_rate_fetcher.save_data_to_db scheduled__2000-03-28T00:00:00+00:00 [queued]>
[2025-06-03T15:16:46.205+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usd_rate_fetcher.save_data_to_db scheduled__2000-03-28T00:00:00+00:00 [queued]>
[2025-06-03T15:16:46.206+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-03T15:16:46.227+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): save_data_to_db> on 2000-03-28 00:00:00+00:00
[2025-06-03T15:16:46.235+0000] {standard_task_runner.py:57} INFO - Started process 10754 to run task
[2025-06-03T15:16:46.259+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'usd_rate_fetcher', 'save_data_to_db', 'scheduled__2000-03-28T00:00:00+00:00', '--job-id', '8399', '--raw', '--subdir', 'DAGS_FOLDER/usd_rate_fetcher.py', '--cfg-path', '/tmp/tmp5f1mwllz']
[2025-06-03T15:16:46.262+0000] {standard_task_runner.py:85} INFO - Job 8399: Subtask save_data_to_db
[2025-06-03T15:16:46.366+0000] {task_command.py:410} INFO - Running <TaskInstance: usd_rate_fetcher.save_data_to_db scheduled__2000-03-28T00:00:00+00:00 [running]> on host 40869fde016f
[2025-06-03T15:16:46.705+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-03T15:16:46.775+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usd_rate_fetcher' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2000-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2000-03-28T00:00:00+00:00'
[2025-06-03T15:16:46.777+0000] {usd_rate_fetcher.py:80} INFO - Received USD rate: {'date': datetime.date(2000, 3, 28), 'content': [{'Фунт стерлингов': 45.11}, {'Доллар США': 28.31}, {'Евро': 27.69}]} for date 2000-03-28
[2025-06-03T15:16:46.805+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-03T15:16:46.810+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usd_rate_fetcher.py", line 94, in save_data_to_db
    """, (execution_date, currency))
psycopg2.errors.UndefinedTable: relation "economic.currency_rates" does not exist
LINE 2:                 SELECT 1 FROM economic.currency_rates 
                                      ^

[2025-06-03T15:16:46.820+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=usd_rate_fetcher, task_id=save_data_to_db, execution_date=20000328T000000, start_date=20250603T151646, end_date=20250603T151646
[2025-06-03T15:16:46.831+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 8399 for task save_data_to_db (relation "economic.currency_rates" does not exist
LINE 2:                 SELECT 1 FROM economic.currency_rates 
                                      ^
; 10754)
[2025-06-03T15:16:46.844+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-03T15:16:46.861+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
