[2025-06-03T09:17:44.286+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usd_rate_fetcher_taskflow.fetch_data_from_api scheduled__2000-01-13T00:00:00+00:00 [queued]>
[2025-06-03T09:17:44.294+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usd_rate_fetcher_taskflow.fetch_data_from_api scheduled__2000-01-13T00:00:00+00:00 [queued]>
[2025-06-03T09:17:44.294+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2025-06-03T09:17:44.305+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_api> on 2000-01-13 00:00:00+00:00
[2025-06-03T09:17:44.309+0000] {standard_task_runner.py:57} INFO - Started process 690 to run task
[2025-06-03T09:17:44.311+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'usd_rate_fetcher_taskflow', 'fetch_data_from_api', 'scheduled__2000-01-13T00:00:00+00:00', '--job-id', '7421', '--raw', '--subdir', 'DAGS_FOLDER/usd_rate_fetcher.py', '--cfg-path', '/tmp/tmpio7kme4l']
[2025-06-03T09:17:44.312+0000] {standard_task_runner.py:85} INFO - Job 7421: Subtask fetch_data_from_api
[2025-06-03T09:17:44.348+0000] {task_command.py:410} INFO - Running <TaskInstance: usd_rate_fetcher_taskflow.fetch_data_from_api scheduled__2000-01-13T00:00:00+00:00 [running]> on host 40869fde016f
[2025-06-03T09:17:44.382+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-03T09:17:44.408+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usd_rate_fetcher_taskflow' AIRFLOW_CTX_TASK_ID='fetch_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2000-01-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2000-01-13T00:00:00+00:00'
[2025-06-03T09:17:44.409+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usd_rate_fetcher.py", line 30, in fetch_data_from_api
    date_str = execution_date.strftime("%d/%m/%Y")
AttributeError: 'str' object has no attribute 'strftime'
[2025-06-03T09:17:44.415+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=usd_rate_fetcher_taskflow, task_id=fetch_data_from_api, execution_date=20000113T000000, start_date=20250603T091744, end_date=20250603T091744
[2025-06-03T09:17:44.422+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7421 for task fetch_data_from_api ('str' object has no attribute 'strftime'; 690)
[2025-06-03T09:17:44.443+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-03T09:17:44.463+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
