[2025-06-03T09:17:55.025+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usd_rate_fetcher_taskflow.fetch_data_from_api scheduled__2000-01-02T00:00:00+00:00 [queued]>
[2025-06-03T09:17:55.040+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usd_rate_fetcher_taskflow.fetch_data_from_api scheduled__2000-01-02T00:00:00+00:00 [queued]>
[2025-06-03T09:17:55.040+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 3
[2025-06-03T09:17:55.057+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_api> on 2000-01-02 00:00:00+00:00
[2025-06-03T09:17:55.102+0000] {standard_task_runner.py:57} INFO - Started process 891 to run task
[2025-06-03T09:17:55.123+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'usd_rate_fetcher_taskflow', 'fetch_data_from_api', 'scheduled__2000-01-02T00:00:00+00:00', '--job-id', '7424', '--raw', '--subdir', 'DAGS_FOLDER/usd_rate_fetcher.py', '--cfg-path', '/tmp/tmpc0t49c3e']
[2025-06-03T09:17:55.125+0000] {standard_task_runner.py:85} INFO - Job 7424: Subtask fetch_data_from_api
[2025-06-03T09:17:55.288+0000] {task_command.py:410} INFO - Running <TaskInstance: usd_rate_fetcher_taskflow.fetch_data_from_api scheduled__2000-01-02T00:00:00+00:00 [running]> on host 40869fde016f
[2025-06-03T09:17:55.622+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-06-03T09:17:55.684+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usd_rate_fetcher_taskflow' AIRFLOW_CTX_TASK_ID='fetch_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2000-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2000-01-02T00:00:00+00:00'
[2025-06-03T09:17:55.685+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usd_rate_fetcher.py", line 30, in fetch_data_from_api
    date_str = execution_date.strftime("%d/%m/%Y")
AttributeError: 'str' object has no attribute 'strftime'
[2025-06-03T09:17:55.693+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=usd_rate_fetcher_taskflow, task_id=fetch_data_from_api, execution_date=20000102T000000, start_date=20250603T091755, end_date=20250603T091755
[2025-06-03T09:17:55.711+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7424 for task fetch_data_from_api ('str' object has no attribute 'strftime'; 891)
[2025-06-03T09:17:55.760+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-06-03T09:17:55.847+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
